### ISSUE TITLE
KeyError: 'transifex_project_name' when updating .tx/config

### ISSUE THREAD

**Issue by ccwang002** [sphinx-doc/sphinx-intl#1]
When I was updating the txconfig using 

```python
$ sphinx-intl create-txconfig
$ sphinx-intl update-txconfig-resources --transifex-project-name python-35-tw
Traceback (most recent call last):
  ...
  File "/Users/liang/.virtualenvs/pydoc/lib/python3.5/site-packages/sphinx_intl/commands.py", line 536, in update_txconfig_resources
    args = [arg % locals() for arg in args_tmpl]
  File "/Users/liang/.virtualenvs/pydoc/lib/python3.5/site-packages/sphinx_intl/commands.py", line 536, in <listcomp>
    args = [arg % locals() for arg in args_tmpl]
KeyError: 'transifex_project_name'
```

It failed with KeyError, which the argument should be passed to the function.
A quick survey showed it might be related with using `locals()` inside list comprehension,

```python
# sphinx_intl/commands.py:536
args = [arg % locals() for arg in args_tmpl]
```

If I change to 

```python
d = locals()
args = [arg % d for arg in args_tmpl]
```

then the code works.

A demo shows this different behavior in Python 2 and 3.

```python
def print_dict(d):
    print(d)

def main():
    a, b = 3, 4
    print_dict(locals())
    [print_dict(locals()) for i in range(2)]

if __name__ == '__main__':
    main()

# python 2.7
# {'a': 3, 'b': 4}
# {'a': 3, 'i': 0, 'b': 4}
# {'a': 3, 'i': 1, 'b': 4}

# python 3.4 / 3.5
# {'a': 3, 'b': 4}
# {'.0': <range_iterator object at 0x1029851e0>, 'i': 0}
# {'.0': <range_iterator object at 0x1029851e0>, 'i': 1}
```

My Python packages versions:

```
Sphinx==1.3.3
sphinx-intl==0.9.7
transifex-client==0.11
```

**Comment by shimizukawa** [comment]
Your investigation helps me fixing the issue. Thanks!
